export const PEOPLE = [
  { name: "Aiden" },
  { name: "Luna" },
  { name: "Milo" },
  { name: "Nova" },
  { name: "Orion" },
  { name: "Ivy" },
  { name: "Theo" },
  { name: "Zara" },
  { name: "Felix" },
  { name: "Aria" },
  { name: "Jasper" },
  { name: "Niko" },
  { name: "Elara" },
  { name: "Rowan" },
  { name: "Soren" },
  { name: "Maya" },
  { name: "Atlas" },
  { name: "Freya" },
  { name: "Leo" },
  { name: "Quinn" },
  { name: "Axel" },
  { name: "Mira" },
  { name: "Kaito" },
  { name: "Noa" },
  { name: "Esme" },
  { name: "Ronan" },
  { name: "Lyra" },
  { name: "Hugo" },
  { name: "Yara" },
  { name: "Finn" },
  { name: "Kaia" },
  { name: "Dante" },
  { name: "Isla" },
  { name: "Remy" },
  { name: "Taro" },
  { name: "Amara" },
  { name: "Silas" },
  { name: "Nina" },
  { name: "Olin" },
  { name: "Petra" },
  { name: "Luca" },
  { name: "Hana" },
  { name: "Bodhi" },
  { name: "Vera" },
  { name: "Kenji" },
  { name: "Alina" },
  { name: "Marco" },
  { name: "Rhea" },
  { name: "Tobias" },
  { name: "Zane" },
];

export const getPerson = ({ name }: { name: string }) =>
  PEOPLE.find((person) => person.name === name);
